# Reach task
Reach-Gazebo-v0:
  policy: "MlpPolicy"
  policy_kwargs:
    net_arch: [128, 64]
  env_wrapper:
    - drl_grasping.envs.randomizers.ManipulationGazeboEnvRandomizer:
        object_random_pose: True
  n_timesteps: 250000
  buffer_size: 50000
  learning_starts: 2500
  batch_size: 128
  learning_rate: 0.0001
  gamma: 0.98
  tau: 0.02
  target_policy_noise: 0.2
  target_noise_clip: 0.5
  train_freq: [1, "episode"]
  gradient_steps: 200
  noise_type: "normal"
  noise_std: 0.1

Reach-ColorImage-Gazebo-v0:
  policy: "CnnPolicy"
  policy_kwargs:
    net_arch: [128, 64]
  env_wrapper:
    - drl_grasping.envs.randomizers.ManipulationGazeboEnvRandomizer:
        camera_pose_rollouts_num: 0
        object_random_pose: True
  n_timesteps: 250000
  buffer_size: 50000
  learning_starts: 2500
  batch_size: 32
  learning_rate: 0.0001
  gamma: 0.98
  tau: 0.02
  target_policy_noise: 0.2
  target_noise_clip: 0.5
  train_freq: [1, "episode"]
  gradient_steps: 200
  noise_type: "normal"
  noise_std: 0.1

Reach-Octree-Gazebo-v0:
  policy: "OctreeCnnPolicy"
  policy_kwargs:
    features_extractor_kwargs:
      depth: 5
      full_depth: 2
      channels_in: 3
      channel_multiplier: 8
      fast_conv: True
      batch_normalization: False
    net_arch: [128, 64]
  env_wrapper:
    - drl_grasping.envs.randomizers.ManipulationGazeboEnvRandomizer:
        camera_pose_rollouts_num: 0
        object_random_pose: True
  n_timesteps: 250000
  buffer_size: 50000
  learning_starts: 2500
  batch_size: 32
  learning_rate: 0.0001
  gamma: 0.98
  tau: 0.02
  target_policy_noise: 0.2
  target_noise_clip: 0.5
  train_freq: [1, "episode"]
  gradient_steps: 200
  noise_type: "normal"
  noise_std: 0.1

Reach-OctreeWithColor-Gazebo-v0:
  policy: "OctreeCnnPolicy"
  policy_kwargs:
    features_extractor_kwargs:
      depth: 5
      full_depth: 2
      channels_in: 6
      channel_multiplier: 16
      fast_conv: True
      batch_normalization: False
    net_arch: [128, 64]
  env_wrapper:
    - drl_grasping.envs.randomizers.ManipulationGazeboEnvRandomizer:
        camera_pose_rollouts_num: 0
        object_random_pose: True
  n_timesteps: 250000
  buffer_size: 50000
  learning_starts: 2500
  batch_size: 32
  learning_rate: 0.0001
  gamma: 0.98
  tau: 0.02
  target_policy_noise: 0.2
  target_noise_clip: 0.5
  train_freq: [1, "episode"]
  gradient_steps: 200
  noise_type: "normal"
  noise_std: 0.1

# Grasp task
Grasp-Octree-Gazebo-v0:
  policy: "OctreeCnnPolicy"
  policy_kwargs:
    features_extractor_kwargs:
      depth: 5
      full_depth: 2
      channels_in: 3
      channel_multiplier: 32
      fast_conv: True
      batch_normalization: False
    net_arch: [128, 96]
  env_wrapper:
    - drl_grasping.envs.randomizers.ManipulationGazeboEnvRandomizer:
        robot_random_joint_positions: False
        camera_pose_rollouts_num: 0
        ground_model_rollouts_num: 1
        object_random_pose: True
        object_models_rollouts_num: 1
  n_timesteps: 1000000
  buffer_size: 75000
  learning_starts: 5000
  batch_size: 64
  learning_rate: 0.0001
  gamma: 0.99
  tau: 0.01
  target_policy_noise: 0.2
  target_noise_clip: 0.5
  train_freq: [1, "episode"]
  gradient_steps: 250
  noise_type: "normal"
  noise_std: 0.25

Grasp-OctreeWithColor-Gazebo-v0:
  policy: "OctreeCnnPolicy"
  policy_kwargs:
    features_extractor_kwargs:
      depth: 5
      full_depth: 2
      channels_in: 6
      channel_multiplier: 64
      fast_conv: True
      batch_normalization: False
    net_arch: [192, 128]
  env_wrapper:
    - drl_grasping.envs.randomizers.ManipulationGazeboEnvRandomizer:
        robot_random_joint_positions: False
        camera_pose_rollouts_num: 0
        ground_model_rollouts_num: 0
        object_random_pose: True
        object_models_rollouts_num: 0
  n_timesteps: 1000000
  buffer_size: 75000
  learning_starts: 5000
  batch_size: 64
  learning_rate: 0.0001
  gamma: 0.99
  tau: 0.01
  target_policy_noise: 0.3
  target_noise_clip: 0.5
  train_freq: [1, "episode"]
  gradient_steps: 250
  noise_type: "normal"
  noise_std: 0.25
